### ISSUE TITLE
Allow installer to be run from the command line

### ISSUE THREAD

**Issue by Lazrius** [oliverpechey/Freelancer-HD-Edition-Installer#121]
I would like to use HD Edition as the base for my Chaos Mod, and for that I want the game to be installed with very specific parameters. I was hoping that I could run the installer via the command line with specific flags and a silent flag to install it with the desired settings, to the right folder, etc..

After looking at a few places it seems that this is possible:
- https://stackoverflow.com/a/48349992
- https://jrsoftware.org/ishelp/index.php?topic=setupcmdline

**Comment by BC46** [comment]
Implemented in https://github.com/oliverpechey/Freelancer-HD-Edition-Installer/pull/132/commits/3d0b8fb44df28b217bae4e51eb8fefd7274970ee. It works by basically calling `FreelancerHDESetup.exe` from the command line like this:
```
FreelancerHDESetup.exe /VERYSILENT /VanillaFlDir="C:\Program Files (x86)\Microsoft Games\Freelancer" /PlanetScape=0 /GraphicsApi=2 /StoryMode=1 /CallSign=7 /DIR="C:\Games\Freelancer HD Edition" 
```

Every single selectable option in the installer can be adjusted by passing the correct argument name and desired value for it.

I have not yet documented which exact values can be entered and what the name of every option is (will do it later). Additionally, I have not tested every single option thoroughly yet, so it would be nice if you could give it a few test runs as well. If needed I can provide you a test build.

**Comment by BC46** [comment]
All good @Lazrius?

**Comment by Lazrius** [comment]
Yep works perfectly!
