### ISSUE TITLE
Entire label text should be clickable

### ISSUE THREAD

**Issue by BC46** [oliverpechey/Freelancer-HD-Edition-Installer#38]
![image](https://user-images.githubusercontent.com/45081813/136857910-e4b9c331-3cd4-476e-8480-ad03638eaa30.png)

In standard HTML, it's possible to check a checkbox by clicking its label text. In the current installer this is also possible. However, it seems that only half of the text is actually clickable, the other part isn't.

I'm not sure if this can be changed in Inno setup installers though.

**Comment by ollieraikkonen** [comment]
We might be able to do some fancy on click event for the label which checks the checkbox. Will leave open but don't think this should be a blocker for 0.4.1

**Comment by BC46** [comment]
Turns out we're not meant to actually create separate `TLabel` elements for each option. Instead, we should use the `Caption` property for elements like `TCheckBox` and `TRadioButton` to set labels directly. Though with this approach the element's `Width` must be increased manually if the caption is too large.
