### ISSUE TITLE
UI freezes during install

### ISSUE THREAD

**Issue by BC46** [oliverpechey/Freelancer-HD-Edition-Installer#95]
During the operations that we perform for the installation (e.g. unzipping and moving files), the UI often freezes.

Some useful sources:
https://stackoverflow.com/questions/32256432/how-to-execute-7zip-without-blocking-the-inno-setup-ui/32266687#32266687
https://stackoverflow.com/questions/14385393/inno-setup-how-to-modify-long-running-script-so-it-will-not-freeze-gui
https://stackoverflow.com/questions/591899/how-do-you-make-inno-setup-not-look-frozen-while-performing-a-long-exec

**Comment by keenanweaver** [comment]
Here's a good Inno installer with nice extraction/no freezing during intensive operations. https://github.com/nipkownix/SH2EE-web-installer/blob/master/wpExtract.iss

Video (doesn't show extract, unfortunately): https://youtu.be/LylafxQta9w?t=45
